export const ENUM_INFECTIOUS_SCREENING = [
    'Positive',
    'Negative',
    'Weakly Positive',
    'Non Reactive',
];

export type LabTestType = 'numeric' | 'text' | 'enum' | 'richtext';

export interface Range {
    low: number;
    high: number;
}

export interface LabTest {
    id: number;
    name: string;
    type: LabTestType;
    category: string;
    subgroup: string | null;
    unit: string | null;
    range: Range | null;
    rangeMale: Range | null;
    rangeFemale: Range | null;
    refText: string | null;
    enumValues?: string[];
    customFooter?: string;
}

export const LAB_TEST: LabTest[] = [
    {
        id: 0,
        name: 'Urea',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: 'mg/dl',
        range: { low: 10, high: 50 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 1,
        name: 'Creatinine',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: 'mg/dl',
        range: { low: 10, high: 50 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 2,
        name: 'Glucose (R)',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: 'mg/dl',
        range: { low: 80, high: 180 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 3,
        name: 'Uric acid',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: 'mg/dl',
        range: { low: 2, high: 7 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 4,
        name: 'e GFR',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: 'mL/min/1.73m²',
        range: { low: 0, high: 60 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 5,
        name: 'Trop-T',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: 'pg/ml',
        range: { low: 0, high: 14 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 6,
        name: 'Sodium',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Serum Electrolyte',
        unit: 'mmol/L',
        range: { low: 135, high: 148 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 7,
        name: 'Potassium',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Serum Electrolyte',
        unit: 'mmol/L',
        range: { low: 3.5, high: 5.3 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 8,
        name: 'Chloride',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Serum Electrolyte',
        unit: 'mmol/L',
        range: { low: 98, high: 107 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 9,
        name: 'Bicarbonate',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Serum Electrolyte',
        unit: 'mmol/L',
        range: { low: 22, high: 28 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 10,
        name: 'Total Bilirubin',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Liver Function Tests',
        unit: 'mg/dl',
        range: { low: 0.2, high: 1 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 11,
        name: 'ALP',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Liver Function Tests',
        unit: 'U/L',
        range: { low: 35, high: 135 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 12,
        name: 'ALT',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Liver Function Tests',
        unit: 'U/L',
        range: { low: 0, high: 40 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 13,
        name: 'AST',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Liver Function Tests',
        unit: 'U/L',
        range: { low: 0, high: 37 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 14,
        name: 'γ-GT',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Liver Function Tests',
        unit: 'U/L',
        range: { low: 0, high: 55 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 15,
        name: 'Total Protein',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'T&D Protein',
        unit: 'g/L',
        range: { low: 55, high: 80 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 16,
        name: 'Albumin',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'T&D Protein',
        unit: 'g/L',
        range: { low: 35, high: 55 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 17,
        name: 'Globulin',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'T&D Protein',
        unit: 'g/L',
        range: { low: 20, high: 40 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 18,
        name: 'Total Cholesterol',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Lipid Profile',
        unit: 'mg/dl',
        range: { low: 135, high: 200 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 19,
        name: 'HDL',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Lipid Profile',
        unit: 'mg/dl',
        range: { low: 30, high: 75 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 20,
        name: 'LDL',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Lipid Profile',
        unit: 'mg/dl',
        range: { low: 0, high: 140 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 21,
        name: 'Triglycerides',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'Lipid Profile',
        unit: 'mg/dl',
        range: { low: 0, high: 165 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 22,
        name: 'ABO Blood Grouping',
        type: 'enum',
        category: 'Biochemistry',
        subgroup: 'Blood Test',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
        enumValues: ['A', 'B', 'AB', 'O'],
    },
    {
        id: 23,
        name: 'Rh (D)',
        type: 'enum',
        category: 'Biochemistry',
        subgroup: 'Blood Test',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
        enumValues: ['Positive', 'Negative'],
    },
    {
        id: 24,
        name: 'Anti HIV(Quali)',
        type: 'enum',
        category: 'Biochemistry',
        subgroup: 'Infectious Screenig',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: '(Rapid Diagnostic Test)',
        enumValues: ['Positive', 'Negative', 'Weakly Positive', 'Non Reactive'],
    },
    {
        id: 25,
        name: 'HBs Ag (Quali)',
        type: 'enum',
        category: 'Biochemistry',
        subgroup: 'Infectious Screenig',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: '(Rapid Diagnostic Test)',
        enumValues: ['Positive', 'Negative', 'Weakly Positive', 'Non Reactive'],
    },
    {
        id: 26,
        name: 'Anti HCV(Quali)',
        type: 'enum',
        category: 'Biochemistry',
        subgroup: 'Infectious Screenig',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: '(Rapid Diagnostic Test)',
        enumValues: ['Positive', 'Negative', 'Weakly Positive', 'Non Reactive'],
    },
    {
        id: 27,
        name: 'VDRL',
        type: 'enum',
        category: 'Biochemistry',
        subgroup: 'Infectious Screenig',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: '(Rapid Diagnostic Test)',
        enumValues: ['Positive', 'Negative', 'Weakly Positive', 'Non Reactive'],
    },
    {
        id: 28,
        name: 'Glucose(FBS)',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'OGTT',
        unit: 'mg/dl',
        range: { low: 65, high: 120 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 29,
        name: 'Glucose(1 hrpp)',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'OGTT',
        unit: 'mg/dl',
        range: { low: 75, high: 180 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 30,
        name: 'Glucose(2 hrpp)',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: 'OGTT',
        unit: 'mg/dl',
        range: { low: 75, high: 180 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 31,
        name: 'H-Pylori(Ag)',
        type: 'enum',
        category: 'Immunology',
        subgroup: null,
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
        enumValues: ['Positive', 'Negative', 'Normal', 'Not-seen'],
    },
    {
        id: 32,
        name: 'PSA(Total)',
        type: 'numeric',
        category: 'Immunology',
        subgroup: 'Tumour Markers',
        unit: 'ng/mL',
        range: { low: 0, high: 4 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 33,
        name: 'AFP',
        type: 'numeric',
        category: 'Immunology',
        subgroup: 'Tumour Markers',
        unit: 'ng/mL',
        range: { low: 0, high: 10 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 34,
        name: 'CA199',
        type: 'numeric',
        category: 'Immunology',
        subgroup: 'Tumour Markers',
        unit: 'U/mL',
        range: { low: 0, high: 36 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 35,
        name: 'TSH',
        type: 'numeric',
        category: 'Immunology',
        subgroup: 'Thyroid Function Test (Free)',
        unit: 'uIU/mL',
        range: { low: 0.35, high: 5.1 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 36,
        name: 'FT3',
        type: 'numeric',
        category: 'Immunology',
        subgroup: 'Thyroid Function Test (Free)',
        unit: 'pmol/L',
        range: { low: 2.76, high: 6.45 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 37,
        name: 'FT4',
        type: 'numeric',
        category: 'Immunology',
        subgroup: 'Thyroid Function Test (Free)',
        unit: 'pmol/L',
        range: { low: 11.2, high: 23.81 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 38,
        name: 'Color',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 39,
        name: 'Apperance',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 40,
        name: 'Sugar',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 41,
        name: 'Protein',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 42,
        name: 'Urobilinogen',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 43,
        name: 'Bilirubin',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 44,
        name: 'Ketone',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 45,
        name: 'Blood',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 46,
        name: 'Leucocyte',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 47,
        name: 'Nitrite',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 48,
        name: 'pH',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 49,
        name: 'Specific gravity',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 50,
        name: 'Epithelial Cells',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: '/ HPF',
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 51,
        name: 'Pus Cells',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: '/ HPF',
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 52,
        name: 'Red Blood Cells',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: '/ HPF',
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 53,
        name: 'Crystals',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 54,
        name: 'Casts',
        type: 'text',
        category: 'Urine Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 55,
        name: 'Other',
        type: 'richtext',
        category: 'Urine Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 56,
        name: 'Color',
        type: 'text',
        category: 'Stool Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 57,
        name: 'Consistency',
        type: 'text',
        category: 'Stool Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 58,
        name: 'Blood',
        type: 'text',
        category: 'Stool Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 59,
        name: 'Mucous',
        type: 'text',
        category: 'Stool Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 60,
        name: 'Reaction',
        type: 'text',
        category: 'Stool Routine Examination',
        subgroup: 'Macroscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 61,
        name: 'Red Blood Cells',
        type: 'text',
        category: 'Stool Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 62,
        name: 'Pus Cells',
        type: 'text',
        category: 'Stool Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: '/ HPF',
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 63,
        name: 'Ova',
        type: 'text',
        category: 'Stool Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: '/ HPF',
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 64,
        name: 'Cysts',
        type: 'text',
        category: 'Stool Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 65,
        name: 'Other',
        type: 'richtext',
        category: 'Stool Routine Examination',
        subgroup: 'Microscopic Examination',
        unit: null,
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 67,
        name: 'Calcium',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: 'mg/dl',
        range: { low: 8.4, high: 10.6 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 68,
        name: 'Phosphate',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: 'mg/dl',
        range: { low: 2.5, high: 4.5 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 69,
        name: 'Amylase',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: 'U/L',
        range: { low: 25, high: 95 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
    },
    {
        id: 70,
        name: 'Direct Bilirubin',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: 'mg/dl',
        range: null,
        rangeMale: null,
        rangeFemale: null,
        refText: '0.6 (<3Month),0.3(>3Month)',
    },
    {
        id: 71,
        name: 'HbA1C',
        type: 'numeric',
        category: 'Biochemistry',
        subgroup: null,
        unit: '%',
        range: { low: 4.0, high: 5.9 },
        rangeMale: null,
        rangeFemale: null,
        refText: null,
        customFooter:
            '<div class="mx-auto w-96"> <h2 class="font-bold text-center pb-2">Result Interpretation</h2> <table class="w-full border-collapse border border-slate-400"> <thead class="bg-slate-200"> <tr> <th class="border border-slate-400 px-2 py-1">Age</th> <th class="border border-slate-400 px-2 py-1"> Reference Dorup </th> </tr> </thead> <tbody> <tr> <td class="border border-slate-400 px-2 py-1"> &gt;18 Yrs(&lt; 5.7) </td> <td class="border border-slate-400 px-2 py-1"> Non Diabetes Adults </td> </tr> <tr> <td class="border border-slate-400 px-2 py-1"> &gt;18 Yrs(5.7 - 6.4) </td> <td class="border border-slate-400 px-2 py-1"> At risks (prediabetes) </td> </tr> <tr> <td class="border border-slate-400 px-2 py-1"> &gt;18 Yrs(&ge;6.5) </td> <td class="border border-slate-400 px-2 py-1"> Diagnosing Daibetes </td> </tr> </tbody> </table> </div>',
    },
];
